[package]
name = "demo-02-blinky-hal"
version = "0.1.0"
authors = ["Alvin Wong <alvinhochun@gmail.com>"]
edition = "2018"

[dependencies]
gd32vf103-pac = "0.4"
gd32vf103xx-hal = "0.4"
panic-halt = "0.2.0"
riscv-rt = "0.8"
